//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicio.PlaceToPlayPSEService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://api.placetopay.com/soap/pse", ConfigurationName="PlaceToPlayPSEService.PlacetoPay_PSEPort")]
    public interface PlacetoPay_PSEPort {
        
        // CODEGEN: El parámetro 'getBankListResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#getBankList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicio.PlaceToPlayPSEService.getBankListResponse getBankList(Servicio.PlaceToPlayPSEService.getBankListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#getBankList", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.getBankListResponse> getBankListAsync(Servicio.PlaceToPlayPSEService.getBankListRequest request);
        
        // CODEGEN: El parámetro 'createTransactionResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#createTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicio.PlaceToPlayPSEService.createTransactionResponse createTransaction(Servicio.PlaceToPlayPSEService.createTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#createTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.createTransactionResponse> createTransactionAsync(Servicio.PlaceToPlayPSEService.createTransactionRequest request);
        
        // CODEGEN: El parámetro 'createTransactionMultiCreditResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#createTransactionMultiCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicio.PlaceToPlayPSEService.createTransactionMultiCreditResponse createTransactionMultiCredit(Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#createTransactionMultiCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.createTransactionMultiCreditResponse> createTransactionMultiCreditAsync(Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest request);
        
        // CODEGEN: El parámetro 'getTransactionInformationResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#getTransactionInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Servicio.PlaceToPlayPSEService.getTransactionInformationResponse getTransactionInformation(Servicio.PlaceToPlayPSEService.getTransactionInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://api.placetopay.com/soap/pse#getTransactionInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.getTransactionInformationResponse> getTransactionInformationAsync(Servicio.PlaceToPlayPSEService.getTransactionInformationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string tranKeyField;
        
        private string seedField;
        
        private Attribute[] additionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tranKey {
            get {
                return this.tranKeyField;
            }
            set {
                this.tranKeyField = value;
                this.RaisePropertyChanged("tranKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
                this.RaisePropertyChanged("seed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Attribute[] additional {
            get {
                return this.additionalField;
            }
            set {
                this.additionalField = value;
                this.RaisePropertyChanged("additional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class Attribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class TransactionInformation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> transactionIDField;
        
        private string sessionIDField;
        
        private string referenceField;
        
        private string requestDateField;
        
        private string bankProcessDateField;
        
        private System.Nullable<bool> onTestField;
        
        private string returnCodeField;
        
        private string trazabilityCodeField;
        
        private System.Nullable<int> transactionCycleField;
        
        private string transactionStateField;
        
        private System.Nullable<int> responseCodeField;
        
        private string responseReasonCodeField;
        
        private string responseReasonTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("transactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string requestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("requestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankProcessDate {
            get {
                return this.bankProcessDateField;
            }
            set {
                this.bankProcessDateField = value;
                this.RaisePropertyChanged("bankProcessDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool> onTest {
            get {
                return this.onTestField;
            }
            set {
                this.onTestField = value;
                this.RaisePropertyChanged("onTest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string trazabilityCode {
            get {
                return this.trazabilityCodeField;
            }
            set {
                this.trazabilityCodeField = value;
                this.RaisePropertyChanged("trazabilityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> transactionCycle {
            get {
                return this.transactionCycleField;
            }
            set {
                this.transactionCycleField = value;
                this.RaisePropertyChanged("transactionCycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string transactionState {
            get {
                return this.transactionStateField;
            }
            set {
                this.transactionStateField = value;
                this.RaisePropertyChanged("transactionState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string responseReasonCode {
            get {
                return this.responseReasonCodeField;
            }
            set {
                this.responseReasonCodeField = value;
                this.RaisePropertyChanged("responseReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string responseReasonText {
            get {
                return this.responseReasonTextField;
            }
            set {
                this.responseReasonTextField = value;
                this.RaisePropertyChanged("responseReasonText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class CreditConcept : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entityCodeField;
        
        private string serviceCodeField;
        
        private System.Nullable<double> amountValueField;
        
        private System.Nullable<double> taxValueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string entityCode {
            get {
                return this.entityCodeField;
            }
            set {
                this.entityCodeField = value;
                this.RaisePropertyChanged("entityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serviceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("serviceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> amountValue {
            get {
                return this.amountValueField;
            }
            set {
                this.amountValueField = value;
                this.RaisePropertyChanged("amountValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> taxValue {
            get {
                return this.taxValueField;
            }
            set {
                this.taxValueField = value;
                this.RaisePropertyChanged("taxValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class PSETransactionMultiCreditRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CreditConcept[] creditsField;
        
        private string bankCodeField;
        
        private string bankInterfaceField;
        
        private string returnURLField;
        
        private string referenceField;
        
        private string descriptionField;
        
        private string languageField;
        
        private string currencyField;
        
        private System.Nullable<double> totalAmountField;
        
        private System.Nullable<double> taxAmountField;
        
        private System.Nullable<double> devolutionBaseField;
        
        private System.Nullable<double> tipAmountField;
        
        private Person payerField;
        
        private Person buyerField;
        
        private Person shippingField;
        
        private string ipAddressField;
        
        private string userAgentField;
        
        private Attribute[] additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public CreditConcept[] credits {
            get {
                return this.creditsField;
            }
            set {
                this.creditsField = value;
                this.RaisePropertyChanged("credits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("bankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankInterface {
            get {
                return this.bankInterfaceField;
            }
            set {
                this.bankInterfaceField = value;
                this.RaisePropertyChanged("bankInterface");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string returnURL {
            get {
                return this.returnURLField;
            }
            set {
                this.returnURLField = value;
                this.RaisePropertyChanged("returnURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("totalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> taxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("taxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> devolutionBase {
            get {
                return this.devolutionBaseField;
            }
            set {
                this.devolutionBaseField = value;
                this.RaisePropertyChanged("devolutionBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> tipAmount {
            get {
                return this.tipAmountField;
            }
            set {
                this.tipAmountField = value;
                this.RaisePropertyChanged("tipAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Person payer {
            get {
                return this.payerField;
            }
            set {
                this.payerField = value;
                this.RaisePropertyChanged("payer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Person buyer {
            get {
                return this.buyerField;
            }
            set {
                this.buyerField = value;
                this.RaisePropertyChanged("buyer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Person shipping {
            get {
                return this.shippingField;
            }
            set {
                this.shippingField = value;
                this.RaisePropertyChanged("shipping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("ipAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
                this.RaisePropertyChanged("userAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Attribute[] additionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
                this.RaisePropertyChanged("additionalData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class Person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentTypeField;
        
        private string documentField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string companyField;
        
        private string emailAddressField;
        
        private string addressField;
        
        private string cityField;
        
        private string provinceField;
        
        private string countryField;
        
        private string phoneField;
        
        private string mobileField;
        
        private string postalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("documentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
                this.RaisePropertyChanged("document");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class PSETransactionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnCodeField;
        
        private string bankURLField;
        
        private string trazabilityCodeField;
        
        private System.Nullable<int> transactionCycleField;
        
        private System.Nullable<int> transactionIDField;
        
        private string sessionIDField;
        
        private string bankCurrencyField;
        
        private System.Nullable<float> bankFactorField;
        
        private System.Nullable<int> responseCodeField;
        
        private string responseReasonCodeField;
        
        private string responseReasonTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankURL {
            get {
                return this.bankURLField;
            }
            set {
                this.bankURLField = value;
                this.RaisePropertyChanged("bankURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string trazabilityCode {
            get {
                return this.trazabilityCodeField;
            }
            set {
                this.trazabilityCodeField = value;
                this.RaisePropertyChanged("trazabilityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> transactionCycle {
            get {
                return this.transactionCycleField;
            }
            set {
                this.transactionCycleField = value;
                this.RaisePropertyChanged("transactionCycle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> transactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("transactionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankCurrency {
            get {
                return this.bankCurrencyField;
            }
            set {
                this.bankCurrencyField = value;
                this.RaisePropertyChanged("bankCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<float> bankFactor {
            get {
                return this.bankFactorField;
            }
            set {
                this.bankFactorField = value;
                this.RaisePropertyChanged("bankFactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("responseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string responseReasonCode {
            get {
                return this.responseReasonCodeField;
            }
            set {
                this.responseReasonCodeField = value;
                this.RaisePropertyChanged("responseReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string responseReasonText {
            get {
                return this.responseReasonTextField;
            }
            set {
                this.responseReasonTextField = value;
                this.RaisePropertyChanged("responseReasonText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class PSETransactionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bankCodeField;
        
        private string bankInterfaceField;
        
        private string returnURLField;
        
        private string referenceField;
        
        private string descriptionField;
        
        private string languageField;
        
        private string currencyField;
        
        private System.Nullable<double> totalAmountField;
        
        private System.Nullable<double> taxAmountField;
        
        private System.Nullable<double> devolutionBaseField;
        
        private System.Nullable<double> tipAmountField;
        
        private Person payerField;
        
        private Person buyerField;
        
        private Person shippingField;
        
        private string ipAddressField;
        
        private string userAgentField;
        
        private Attribute[] additionalDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("bankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankInterface {
            get {
                return this.bankInterfaceField;
            }
            set {
                this.bankInterfaceField = value;
                this.RaisePropertyChanged("bankInterface");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string returnURL {
            get {
                return this.returnURLField;
            }
            set {
                this.returnURLField = value;
                this.RaisePropertyChanged("returnURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("totalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> taxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
                this.RaisePropertyChanged("taxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> devolutionBase {
            get {
                return this.devolutionBaseField;
            }
            set {
                this.devolutionBaseField = value;
                this.RaisePropertyChanged("devolutionBase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> tipAmount {
            get {
                return this.tipAmountField;
            }
            set {
                this.tipAmountField = value;
                this.RaisePropertyChanged("tipAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Person payer {
            get {
                return this.payerField;
            }
            set {
                this.payerField = value;
                this.RaisePropertyChanged("payer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Person buyer {
            get {
                return this.buyerField;
            }
            set {
                this.buyerField = value;
                this.RaisePropertyChanged("buyer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Person shipping {
            get {
                return this.shippingField;
            }
            set {
                this.shippingField = value;
                this.RaisePropertyChanged("shipping");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("ipAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userAgent {
            get {
                return this.userAgentField;
            }
            set {
                this.userAgentField = value;
                this.RaisePropertyChanged("userAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Attribute[] additionalData {
            get {
                return this.additionalDataField;
            }
            set {
                this.additionalDataField = value;
                this.RaisePropertyChanged("additionalData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.placetopay.com/soap/pse")]
    public partial class Bank : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bankCodeField;
        
        private string bankNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("bankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
                this.RaisePropertyChanged("bankName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBankList", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class getBankListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Servicio.PlaceToPlayPSEService.Authentication auth;
        
        public getBankListRequest() {
        }
        
        public getBankListRequest(Servicio.PlaceToPlayPSEService.Authentication auth) {
            this.auth = auth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBankListResponse", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class getBankListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Servicio.PlaceToPlayPSEService.Bank[] getBankListResult;
        
        public getBankListResponse() {
        }
        
        public getBankListResponse(Servicio.PlaceToPlayPSEService.Bank[] getBankListResult) {
            this.getBankListResult = getBankListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTransaction", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class createTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.PSETransactionRequest transaction;
        
        public createTransactionRequest() {
        }
        
        public createTransactionRequest(Servicio.PlaceToPlayPSEService.Authentication auth, Servicio.PlaceToPlayPSEService.PSETransactionRequest transaction) {
            this.auth = auth;
            this.transaction = transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTransactionResponse", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class createTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.PSETransactionResponse createTransactionResult;
        
        public createTransactionResponse() {
        }
        
        public createTransactionResponse(Servicio.PlaceToPlayPSEService.PSETransactionResponse createTransactionResult) {
            this.createTransactionResult = createTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTransactionMultiCredit", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class createTransactionMultiCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.PSETransactionMultiCreditRequest transaction;
        
        public createTransactionMultiCreditRequest() {
        }
        
        public createTransactionMultiCreditRequest(Servicio.PlaceToPlayPSEService.Authentication auth, Servicio.PlaceToPlayPSEService.PSETransactionMultiCreditRequest transaction) {
            this.auth = auth;
            this.transaction = transaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createTransactionMultiCreditResponse", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class createTransactionMultiCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.PSETransactionResponse createTransactionMultiCreditResult;
        
        public createTransactionMultiCreditResponse() {
        }
        
        public createTransactionMultiCreditResponse(Servicio.PlaceToPlayPSEService.PSETransactionResponse createTransactionMultiCreditResult) {
            this.createTransactionMultiCreditResult = createTransactionMultiCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionInformation", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class getTransactionInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.Authentication auth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int transactionID;
        
        public getTransactionInformationRequest() {
        }
        
        public getTransactionInformationRequest(Servicio.PlaceToPlayPSEService.Authentication auth, int transactionID) {
            this.auth = auth;
            this.transactionID = transactionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionInformationResponse", WrapperNamespace="https://api.placetopay.com/soap/pse", IsWrapped=true)]
    public partial class getTransactionInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.placetopay.com/soap/pse", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicio.PlaceToPlayPSEService.TransactionInformation getTransactionInformationResult;
        
        public getTransactionInformationResponse() {
        }
        
        public getTransactionInformationResponse(Servicio.PlaceToPlayPSEService.TransactionInformation getTransactionInformationResult) {
            this.getTransactionInformationResult = getTransactionInformationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlacetoPay_PSEPortChannel : Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlacetoPay_PSEPortClient : System.ServiceModel.ClientBase<Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort>, Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort {
        
        public PlacetoPay_PSEPortClient() {
        }
        
        public PlacetoPay_PSEPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlacetoPay_PSEPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlacetoPay_PSEPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlacetoPay_PSEPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicio.PlaceToPlayPSEService.getBankListResponse Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.getBankList(Servicio.PlaceToPlayPSEService.getBankListRequest request) {
            return base.Channel.getBankList(request);
        }
        
        public Servicio.PlaceToPlayPSEService.Bank[] getBankList(Servicio.PlaceToPlayPSEService.Authentication auth) {
            Servicio.PlaceToPlayPSEService.getBankListRequest inValue = new Servicio.PlaceToPlayPSEService.getBankListRequest();
            inValue.auth = auth;
            Servicio.PlaceToPlayPSEService.getBankListResponse retVal = ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).getBankList(inValue);
            return retVal.getBankListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.getBankListResponse> Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.getBankListAsync(Servicio.PlaceToPlayPSEService.getBankListRequest request) {
            return base.Channel.getBankListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.getBankListResponse> getBankListAsync(Servicio.PlaceToPlayPSEService.Authentication auth) {
            Servicio.PlaceToPlayPSEService.getBankListRequest inValue = new Servicio.PlaceToPlayPSEService.getBankListRequest();
            inValue.auth = auth;
            return ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).getBankListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicio.PlaceToPlayPSEService.createTransactionResponse Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.createTransaction(Servicio.PlaceToPlayPSEService.createTransactionRequest request) {
            return base.Channel.createTransaction(request);
        }
        
        public Servicio.PlaceToPlayPSEService.PSETransactionResponse createTransaction(Servicio.PlaceToPlayPSEService.Authentication auth, Servicio.PlaceToPlayPSEService.PSETransactionRequest transaction) {
            Servicio.PlaceToPlayPSEService.createTransactionRequest inValue = new Servicio.PlaceToPlayPSEService.createTransactionRequest();
            inValue.auth = auth;
            inValue.transaction = transaction;
            Servicio.PlaceToPlayPSEService.createTransactionResponse retVal = ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).createTransaction(inValue);
            return retVal.createTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.createTransactionResponse> Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.createTransactionAsync(Servicio.PlaceToPlayPSEService.createTransactionRequest request) {
            return base.Channel.createTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.createTransactionResponse> createTransactionAsync(Servicio.PlaceToPlayPSEService.Authentication auth, Servicio.PlaceToPlayPSEService.PSETransactionRequest transaction) {
            Servicio.PlaceToPlayPSEService.createTransactionRequest inValue = new Servicio.PlaceToPlayPSEService.createTransactionRequest();
            inValue.auth = auth;
            inValue.transaction = transaction;
            return ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).createTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicio.PlaceToPlayPSEService.createTransactionMultiCreditResponse Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.createTransactionMultiCredit(Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest request) {
            return base.Channel.createTransactionMultiCredit(request);
        }
        
        public Servicio.PlaceToPlayPSEService.PSETransactionResponse createTransactionMultiCredit(Servicio.PlaceToPlayPSEService.Authentication auth, Servicio.PlaceToPlayPSEService.PSETransactionMultiCreditRequest transaction) {
            Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest inValue = new Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest();
            inValue.auth = auth;
            inValue.transaction = transaction;
            Servicio.PlaceToPlayPSEService.createTransactionMultiCreditResponse retVal = ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).createTransactionMultiCredit(inValue);
            return retVal.createTransactionMultiCreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.createTransactionMultiCreditResponse> Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.createTransactionMultiCreditAsync(Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest request) {
            return base.Channel.createTransactionMultiCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.createTransactionMultiCreditResponse> createTransactionMultiCreditAsync(Servicio.PlaceToPlayPSEService.Authentication auth, Servicio.PlaceToPlayPSEService.PSETransactionMultiCreditRequest transaction) {
            Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest inValue = new Servicio.PlaceToPlayPSEService.createTransactionMultiCreditRequest();
            inValue.auth = auth;
            inValue.transaction = transaction;
            return ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).createTransactionMultiCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicio.PlaceToPlayPSEService.getTransactionInformationResponse Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.getTransactionInformation(Servicio.PlaceToPlayPSEService.getTransactionInformationRequest request) {
            return base.Channel.getTransactionInformation(request);
        }
        
        public Servicio.PlaceToPlayPSEService.TransactionInformation getTransactionInformation(Servicio.PlaceToPlayPSEService.Authentication auth, int transactionID) {
            Servicio.PlaceToPlayPSEService.getTransactionInformationRequest inValue = new Servicio.PlaceToPlayPSEService.getTransactionInformationRequest();
            inValue.auth = auth;
            inValue.transactionID = transactionID;
            Servicio.PlaceToPlayPSEService.getTransactionInformationResponse retVal = ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).getTransactionInformation(inValue);
            return retVal.getTransactionInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.getTransactionInformationResponse> Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort.getTransactionInformationAsync(Servicio.PlaceToPlayPSEService.getTransactionInformationRequest request) {
            return base.Channel.getTransactionInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Servicio.PlaceToPlayPSEService.getTransactionInformationResponse> getTransactionInformationAsync(Servicio.PlaceToPlayPSEService.Authentication auth, int transactionID) {
            Servicio.PlaceToPlayPSEService.getTransactionInformationRequest inValue = new Servicio.PlaceToPlayPSEService.getTransactionInformationRequest();
            inValue.auth = auth;
            inValue.transactionID = transactionID;
            return ((Servicio.PlaceToPlayPSEService.PlacetoPay_PSEPort)(this)).getTransactionInformationAsync(inValue);
        }
    }
}
